version: '3.8'

services:
  git-hooks:
    image: git-hooks
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
